names = {...
    'Cs-137_14min',...
    'background_1h_20m',...
    'Eu-152_12m',...
    'Na-22_16m'...
    };
dataArray = zeros(length(names),8192);
for ind=1:length(names)
    dataArray(ind,:) = importrawdata(char(names(ind)));
end
clear ind
